const AUTH_API_URL="https://script.google.com/macros/s/AKfycbxWB-6R33-_lMdxYAni197Qkh_2EFTZuG1I8R_bnp1DqGbozbhKCXkbQVLr2xFXOC7ubg/exec";
const posts=[
 {title:"좋은 코드는 읽는 사람을 배려한다",category:"개발",date:"2026. 09. 05",read:"6분",excerpt:"코드는 컴퓨터보다 사람이 더 자주 읽습니다. 협업하며 배운 읽기 좋은 코드의 작은 원칙들을 정리했습니다.",visual:"{ clean code }"},
 {title:"사이드 프로젝트를 끝내는 방법",category:"개발",date:"2026. 08. 28",read:"8분",excerpt:"거창한 계획보다 완성의 경험이 중요합니다. 범위를 줄이고 끝까지 배포하기 위해 사용한 현실적인 방법들.",visual:"ship →"},
 {title:"여름의 끝에서 발견한 것들",category:"일상",date:"2026. 08. 19",read:"4분",excerpt:"유난히 길었던 여름, 익숙한 동네를 천천히 걸으며 새롭게 보게 된 장면과 마음에 관한 기록입니다.",visual:"08 / 19"},
 {title:"꾸준함에 재능이 필요한가요",category:"생각",date:"2026. 08. 11",read:"5분",excerpt:"매일 잘하는 대신 다시 돌아오는 연습. 꾸준함을 의지가 아닌 환경의 문제로 바라봅니다.",visual:"again."},
 {title:"CSS Grid로 만드는 유연한 레이아웃",category:"개발",date:"2026. 07. 30",read:"7분",excerpt:"복잡한 미디어 쿼리를 줄이고 콘텐츠에 맞춰 자연스럽게 반응하는 그리드 패턴을 소개합니다.",visual:"# grid"},
 {title:"느리게 읽는 시간",category:"일상",date:"2026. 07. 18",read:"3분",excerpt:"속도에서 잠시 벗어나 문장 하나를 오래 바라보는 일이 건네준 뜻밖의 여유에 대하여.",visual:"pause"}
];
const nav=document.querySelector(".site-nav"),toggle=document.querySelector(".menu-toggle");
if(toggle&&nav){toggle.addEventListener("click",()=>{const open=nav.classList.toggle("is-open");toggle.setAttribute("aria-expanded",String(open));toggle.setAttribute("aria-label",open?"메뉴 닫기":"메뉴 열기")});nav.addEventListener("click",e=>{if(e.target.closest("a")){nav.classList.remove("is-open");toggle.setAttribute("aria-expanded","false")}})}
const list=document.querySelector("#post-list"),search=document.querySelector("#post-search"),filters=document.querySelectorAll("[data-filter]"),empty=document.querySelector("#empty-state"),more=document.querySelector("#load-more");let active="all",visible=4;
function renderPosts(){if(!list)return;const query=(search?.value||"").trim().toLowerCase(),filtered=posts.filter(p=>(active==="all"||p.category===active)&&(p.title+p.excerpt).toLowerCase().includes(query));list.innerHTML=filtered.slice(0,visible).map(p=>`<article class="post-item"><div class="post-content"><div class="post-meta"><span class="category">${p.category}</span><span>${p.date}</span><span>· ${p.read}</span></div><h3><a href="post-detail.html">${p.title}</a></h3><p class="post-excerpt">${p.excerpt}</p></div><a class="post-thumb placeholder" href="post-detail.html" aria-label="${p.title} 읽기">${p.visual}</a></article>`).join("");if(empty)empty.hidden=filtered.length>0;if(more)more.hidden=visible>=filtered.length}
filters.forEach(btn=>btn.addEventListener("click",()=>{filters.forEach(b=>b.classList.remove("is-active"));btn.classList.add("is-active");active=btn.dataset.filter;visible=4;renderPosts()}));search?.addEventListener("input",()=>{visible=4;renderPosts()});more?.addEventListener("click",()=>{visible+=2;renderPosts()});renderPosts();
document.querySelectorAll("[data-demo-form]").forEach(form=>form.addEventListener("submit",e=>{e.preventDefault();const status=form.querySelector(".form-status")||document.querySelector(`#${form.dataset.status}`);if(form.checkValidity()){if(status)status.textContent=form.dataset.message||"완료되었습니다.";form.reset()}}));
document.querySelectorAll(".password-toggle").forEach(btn=>btn.addEventListener("click",()=>{const input=btn.previousElementSibling;input.type=input.type==="password"?"text":"password";btn.textContent=input.type==="password"?"보기":"숨김"}));
function showAuthMessage(form,message,isError=false){const box=form.querySelector(".success-box");if(!box)return;box.hidden=false;box.classList.toggle("is-error",isError);box.textContent=message}
function validateAuthForm(form){let valid=true;form.querySelectorAll("[required]").forEach(input=>{const error=input.closest(".field")?.querySelector(".field-error");if((input.type==="checkbox"&&!input.checked)||!input.value.trim()){valid=false;if(error)error.textContent="필수 입력 항목입니다."}else if(input.type==="email"&&!input.validity.valid){valid=false;if(error)error.textContent="올바른 이메일을 입력해 주세요."}else if(input.name==="password"&&(input.value.length<8||!/[A-Za-z]/.test(input.value)||!/[0-9]/.test(input.value))){valid=false;if(error)error.textContent="영문과 숫자를 포함해 8자 이상 입력해 주세요."}else if(error)error.textContent=""});const password=form.querySelector("[name=password]"),confirm=form.querySelector("[name=passwordConfirm]");if(confirm&&password?.value!==confirm.value){valid=false;confirm.closest(".field").querySelector(".field-error").textContent="비밀번호가 일치하지 않습니다."}if(!valid&&form.querySelector("[name=terms]")&&!form.querySelector("[name=terms]").checked)showAuthMessage(form,"이용약관과 개인정보 처리방침에 동의해 주세요.",true);return valid}
async function authRequest(payload){const response=await fetch(AUTH_API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});if(!response.ok)throw new Error("인증 서버에 연결하지 못했습니다.");return response.json()}
document.querySelectorAll(".auth-form").forEach(form=>form.addEventListener("submit",async e=>{e.preventDefault();if(!validateAuthForm(form))return;const action=form.dataset.authAction,button=form.querySelector("[type=submit]"),originalText=button.textContent,formData=new FormData(form);button.disabled=true;button.textContent=action==="login"?"로그인 중...":"계정 생성 중...";showAuthMessage(form,"요청을 처리하고 있습니다.");try{const payload={action,email:formData.get("email"),password:formData.get("password")};if(action==="signup"){payload.name=formData.get("name");payload.nickname=formData.get("nickname")}const result=await authRequest(payload);if(!result.ok)throw new Error(result.message||"요청을 처리하지 못했습니다.");if(action==="login"){const storage=formData.get("remember")?"local":"session";const target=storage==="local"?localStorage:sessionStorage;const other=storage==="local"?sessionStorage:localStorage;other.removeItem("blogAuthToken");other.removeItem("blogAuthUser");target.setItem("blogAuthToken",result.data.token);target.setItem("blogAuthUser",JSON.stringify(result.data.user));showAuthMessage(form,"로그인되었습니다. 프로필로 이동합니다.");setTimeout(()=>location.href="profile.html",700)}else{form.reset();showAuthMessage(form,"회원가입이 완료되었습니다. 로그인 페이지로 이동합니다.");setTimeout(()=>location.href="login.html",900)}}catch(error){showAuthMessage(form,error.message||"인증 서버와 통신하지 못했습니다.",true)}finally{button.disabled=false;button.textContent=originalText}}));
function getStoredAuth(){const storage=localStorage.getItem("blogAuthToken")?localStorage:sessionStorage;return{storage,token:storage.getItem("blogAuthToken"),user:storage.getItem("blogAuthUser")}}
const storedAuth=getStoredAuth();if(storedAuth.token){document.querySelectorAll('a[href="login.html"]').forEach(link=>{link.textContent="로그아웃";link.href="#logout";link.addEventListener("click",async e=>{e.preventDefault();try{await authRequest({action:"logout",token:storedAuth.token})}finally{storedAuth.storage.removeItem("blogAuthToken");storedAuth.storage.removeItem("blogAuthUser");location.href="index.html"}})})}
const like=document.querySelector("[data-like]");like?.addEventListener("click",()=>{like.classList.toggle("is-active");like.setAttribute("aria-pressed",String(like.classList.contains("is-active")));like.textContent=like.classList.contains("is-active")?"♥":"♡"});
const copy=document.querySelector("[data-copy]");copy?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(location.href);copy.textContent="✓";setTimeout(()=>copy.textContent="↗",1400)}catch{copy.textContent="!"}});
const editor=document.querySelector(".editor-form");if(editor){const title=editor.querySelector(".title-input"),summary=editor.querySelector(".summary-input"),body=editor.querySelector(".body-input"),category=editor.querySelector(".editor-category"),status=document.querySelector(".draft-status"),key="blog-draft";try{const draft=JSON.parse(localStorage.getItem(key));if(draft){title.value=draft.title||"";summary.value=draft.summary||"";body.value=draft.body||"";category.value=draft.category||"개발"}}catch{}const save=()=>{localStorage.setItem(key,JSON.stringify({title:title.value,summary:summary.value,body:body.value,category:category.value}));status.textContent=`${new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})} 임시저장됨`};document.querySelector("[data-save]")?.addEventListener("click",save);editor.addEventListener("submit",e=>{e.preventDefault();if(!title.value.trim()||!body.value.trim()){status.textContent="제목과 본문을 입력해 주세요.";return}save();status.textContent="발행 준비가 완료되었습니다. (데모)"});document.querySelectorAll("[data-format]").forEach(btn=>btn.addEventListener("click",()=>{const mark=btn.dataset.format,start=body.selectionStart,end=body.selectionEnd,selected=body.value.slice(start,end);body.setRangeText(mark+selected+mark,start,end,"select");body.focus()}))}
